function initialize(obj)
% INITIALIZE  Initializes the AMDParamsPanel objects.
%
% Syntax:
% INITIALIZE(obj)
%
% Description:
% Called from the object's constructor, this function does all the basic
% initialization of widgets and internal variables.
%
% Input:
% obj (dynamical.ui.objects.AMDParamsPanel) - The FileInfoPanel object to
%     initialize.

narginchk(1, 1);

obj.Title = 'AMD Parameters    ';
if ismac
    obj.FontSize = 14;
else
    obj.FontSize = 12;
end
%obj.MinimizeFcn = {@dynamical.ui.objects.AMDParamsPanel.minimizePanel, obj};
% s = uix.ScrollingPanel('Parent', obj);
obj.MainVBox = uix.VBox('Parent', obj);

if ismac
    defaults.fontSize = 12;
else
    defaults.fontSize = 10;
end
defaults.widths = [100, 125];
defaults.height = 30;
defaults.padding = 5;
defaults.spacing = 10;
defaults.enable = 'on';

% Start Time
obj.StartTimeHBox = uix.HBox('Parent', obj.MainVBox, ...
    'Padding', defaults.padding, ...
    'Spacing', defaults.spacing);
hLabel(1) = uicontrol(obj.StartTimeHBox, ...
    'FontSize', defaults.fontSize, ...
    'HorizontalAlignment', 'left', ...
    'String', 'Start Time (s):', ...
    'Style', 'text');
obj.StartTimeEdit = uicontrol(obj.StartTimeHBox, ...
    'Callback', @obj.editCallback, ...
    'Enable', defaults.enable, ...
    'FontSize', defaults.fontSize, ...
    'KeyPressFcn', @obj.editKeyPressFcn, ...
    'Style', 'edit', ...
    'UserData', 'StartTime');
obj.StartTimeHBox.Widths = defaults.widths;

% Stop Time
obj.StopTimeHBox = uix.HBox('Parent', obj.MainVBox, ...
    'Padding', defaults.padding, ...
    'Spacing', defaults.spacing);
hLabel(end+1) = uicontrol(obj.StopTimeHBox, ...
    'FontSize', defaults.fontSize, ...
    'HorizontalAlignment', 'left', ...
    'String', 'Stop Time (s):', ...
    'Style', 'text');
obj.StopTimeEdit = uicontrol(obj.StopTimeHBox, ...
    'Callback', @obj.editCallback, ...
    'KeyPressFcn', @obj.editKeyPressFcn, ...
    'Enable', defaults.enable, ...
    'FontSize', defaults.fontSize, ...
    'Style', 'edit', ...
    'UserData', 'StopTime');
obj.StopTimeHBox.Widths = defaults.widths;

% Window Size
obj.WindowHBox = uix.HBox('Parent', obj.MainVBox, ...
    'Padding', defaults.padding, ...
    'Spacing', defaults.spacing);
hLabel(end+1) = uicontrol(obj.WindowHBox, ...
    'FontSize', defaults.fontSize, ...
    'HorizontalAlignment', 'left', ...
    'String', 'Window (s):', ...
    'Style', 'text');
obj.WindowEdit = uicontrol(obj.WindowHBox, ...
    'Callback', @obj.editCallback, ...
    'Enable', defaults.enable, ...
    'FontSize', defaults.fontSize, ...
    'KeyPressFcn', @obj.editKeyPressFcn, ...
    'String', 60, ...
    'Style', 'edit', ...
    'UserData', 'WindowSize');
obj.WindowSize = 60;
obj.WindowHBox.Widths = defaults.widths;

% Window Step
obj.WindowStepHBox = uix.HBox('Parent', obj.MainVBox, ...
    'Padding', defaults.padding, ...
    'Spacing', defaults.spacing);
hLabel(end+1) = uicontrol(obj.WindowStepHBox, ...
    'FontSize', defaults.fontSize, ...
    'HorizontalAlignment', 'left', ...
    'String', 'Window Step(s):', ...
    'Style', 'text');
obj.WindowStepEdit = uicontrol(obj.WindowStepHBox, ...
    'Callback', @obj.editCallback, ...
    'Enable', defaults.enable, ...
    'FontSize', defaults.fontSize, ...
    'KeyPressFcn', @obj.editKeyPressFcn, ...
    'String', 60, ...
    'Style', 'edit', ...
    'UserData', 'WindowStep');
obj.WindowStep = 60;
obj.WindowStepHBox.Widths = defaults.widths;

% Minimum Persistence
obj.MinPersistenceHBox = uix.HBox('Parent', obj.MainVBox, ...
    'Padding', defaults.padding, ...
    'Spacing', defaults.spacing);
hLabel(end+1) = uicontrol(obj.MinPersistenceHBox, ...
    'FontSize', defaults.fontSize, ...
    'HorizontalAlignment', 'left', ...
    'String', 'Persistence:', ...
    'Style', 'text');
obj.MinPersistenceEdit = uicontrol(obj.MinPersistenceHBox, ...
    'Callback', @obj.editCallback, ...
    'Enable', defaults.enable, ...
    'FontSize', defaults.fontSize, ...
    'KeyPressFcn', @obj.editKeyPressFcn, ...
    'String', 0, ...
    'Style', 'edit', ...
    'UserData', 'MinPersistence');
obj.MinPersistence = 0;
obj.MinPersistenceHBox.Widths = defaults.widths;

% Minimum spike count
obj.MinSpikeCountHBox = uix.HBox('Parent', obj.MainVBox, ...
    'Padding', defaults.padding, ...
    'Spacing', defaults.spacing);
hLabel(end+1) = uicontrol(obj.MinSpikeCountHBox, ...
    'FontSize', defaults.fontSize, ...
    'HorizontalAlignment', 'left', ...
    'String', 'Min Spikes:', ...
    'Style', 'text');
obj.MinSpikeCountEdit = uicontrol(obj.MinSpikeCountHBox, ...
    'Callback', @obj.editCallback, ...
    'Enable', defaults.enable, ...
    'FontSize', defaults.fontSize, ...
    'KeyPressFcn', @obj.editKeyPressFcn, ...
    'String', 6, ...
    'Style', 'edit', ...
    'UserData', 'MinSpikeCount');
obj.MinSpikeCount = 6;
obj.MinSpikeCountHBox.Widths = defaults.widths;

% Minimum number of valid neurons per window.
obj.MinValidNeuronsHBox = uix.HBox('Parent', obj.MainVBox, ...
    'Padding', defaults.padding, ...
    'Spacing', defaults.spacing);
hLabel(end+1) = uicontrol(obj.MinValidNeuronsHBox, ...
    'FontSize', defaults.fontSize, ...
    'HorizontalAlignment', 'left', ...
    'String', 'Min Neurons:', ...
    'Style', 'text');
obj.MinValidNeuronsEdit = uicontrol(obj.MinValidNeuronsHBox, ...
    'Callback', @obj.editCallback, ...
    'Enable', defaults.enable, ...
    'FontSize', defaults.fontSize, ...
    'KeyPressFcn', @obj.editKeyPressFcn, ...
    'String', 3, ...
    'Style', 'edit', ...
    'UserData', 'MinValidNeurons');
obj.MinValidNeurons = 3;
obj.MinValidNeuronsHBox.Widths = defaults.widths;

% Interval List Box - Setting Mix-Max > 1 allows multiple selection.
obj.IntervalHBox = uix.HBox('Parent', obj.MainVBox, ...
    'Padding', defaults.padding, ...
    'Spacing', defaults.spacing);
hLabel(end+1) = uicontrol(obj.IntervalHBox, ...
    'FontSize', defaults.fontSize, ...
    'HorizontalAlignment', 'left', ...
    'String', 'Intervals:', ...
    'Style', 'text');
obj.IntervalListBox = uicontrol(obj.IntervalHBox, 'Style', 'listbox');
obj.IntervalListBox.Max = 10;
obj.IntervalListBox.Min = 1;
obj.IntervalHBox.Widths = defaults.widths;

% Stability Mode
obj.StabilityMethodBGroup = uibuttongroup('Parent', obj.MainVBox, ...
    'BorderType', 'none', ...
    'FontSize', defaults.fontSize, ...
    'SelectionChangedFcn', @obj.processButtonGroupCallback, ...
    'Title', 'Stability Method', ...
    'UserData', 'StabilityMethod');
uicontrol(obj.StabilityMethodBGroup, ...
    'FontSize', defaults.fontSize, ...
    'Position', [5 0 75 defaults.height], ...
    'Style', 'radiobutton',...
    'String', 'Neighbor');
uicontrol(obj.StabilityMethodBGroup, ...
    'FontSize', defaults.fontSize, ...
    'Position', [95 0 75 defaults.height], ...
    'Style', 'radiobutton', ...
    'String', 'All');
obj.StabilityMethod = 'Neighbor';

% Parallel Mode
obj.ParallelHBox = uix.HBox('Parent', obj.MainVBox, ...
    'Padding', defaults.padding, ...
    'Spacing', defaults.spacing);
obj.ParallelCheckBox = uicontrol(obj.ParallelHBox, ...
    'Callback', @obj.checkboxCallback, ...
    'FontSize', defaults.fontSize, ...
    'String', 'Parallel Mode', ...
    'Style', 'checkbox', ...
    'UserData', 'Parallel', ...
    'Value', true);
obj.Parallel = true;

% Add a spacer element to push the button we're getting ready to add to the
% bottom of the panel.
uix.Empty('Parent', obj.MainVBox);

obj.ProcessButton = uicontrol(obj.MainVBox, ...
    'Callback', @obj.processButtonCallback, ...
    'Enable', 'off', ...
    'FontSize', defaults.fontSize, ...
    'String', 'Process', ...
    'Style', 'pushbutton');

obj.MainVBox.Heights = [ ...
    repmat(defaults.height, 1, length(hLabel)-1), ... % Param boxes
    100, ...                 % Interval list box
    defaults.height*1.5, ... % Stability mode
    defaults.height, ...     % Parallel toggle
    -1, ...                  % Spacer
    30];                     % Process button

% for i = 1:length(hLabel)
%     hLabel(i).Position(2) = 7;
% end
