function initialize(obj)
% INITIALIZE  Initializes a FileInfoPanel objects.
%
% Syntax:
% INITIALIZE(obj)
%
% Description:
% Called from the object's constructor, this function does all the basic
% initialization of widgets and internal variables.
%
% Input:
% obj (dynamical.ui.objects.FileInfoPanel) - The FileInfoPanel object to
%     initialize.

narginchk(1, 1);

obj.Title = 'File Info    ';
if ismac
    obj.FontSize = 14;
else
    obj.FontSize = 12;
end

obj.MainVBox = uix.VBox('Parent', obj);

if ismac
    defaults.fontSize = 12;
else
    defaults.fontSize = 10;
end
defaults.widths = [100, 125];
defaults.height = 30;
defaults.padding = 5;
defaults.spacing = 10;
defaults.enable = 'inactive';
%defaults.enable = 'on';

% Filename
obj.FileNameHBox = uix.HBox('Parent', obj.MainVBox, ...
    'Padding', defaults.padding, ...
    'Spacing', defaults.spacing);
obj.FileNameLabel = uicontrol(obj.FileNameHBox, ...
    'FontSize', defaults.fontSize, ...
    'HorizontalAlignment', 'left', ...
    'String', 'Filename: ', ...
    'Style', 'text');
hLabel(1) = obj.FileNameLabel;
obj.FileNameEdit = uicontrol(obj.FileNameHBox, ...
    'Enable', defaults.enable, ...
    'FontSize', defaults.fontSize-2, ...
    'Style', 'edit');
obj.FileNameHBox.Widths = defaults.widths;

% Start Time
obj.FileStartHBox = uix.HBox('Parent', obj.MainVBox, ...
    'Padding', defaults.padding, ...
    'Spacing', defaults.spacing);
hLabel(end+1) = uicontrol(obj.FileStartHBox, ...
    'FontSize', defaults.fontSize, ...
    'HorizontalAlignment', 'left', ...
    'String', 'Start Time (s): ', ...
    'Style', 'text');
obj.FileStartEdit = uicontrol(obj.FileStartHBox, ...
    'Enable', defaults.enable, ...
    'FontSize', defaults.fontSize, ...
    'Style', 'edit');
obj.FileStartHBox.Widths = defaults.widths;

% End Time
obj.FileEndHBox = uix.HBox('Parent', obj.MainVBox, ...
    'Padding', defaults.padding, ...
    'Spacing', defaults.spacing);
hLabel(end+1) = uicontrol(obj.FileEndHBox, ...
    'FontSize', defaults.fontSize, ...
    'HorizontalAlignment', 'left', ...
    'String', 'End Time (s): ', ...
    'Style', 'text');
obj.FileEndEdit = uicontrol(obj.FileEndHBox, ...
    'Enable', defaults.enable, ...
    'FontSize', defaults.fontSize, ...
    'Style', 'edit');
obj.FileEndHBox.Widths = defaults.widths;

% Frequency
obj.FileFreqHBox = uix.HBox('Parent', obj.MainVBox, ...
    'Padding', defaults.padding, ...
    'Spacing', defaults.spacing);
hLabel(end+1) = uicontrol(obj.FileFreqHBox, ...
    'FontSize', defaults.fontSize, ...
    'HorizontalAlignment', 'left', ...
    'String', 'Frequency (Hz): ', ...
    'Style', 'text');
obj.FileFreqEdit = uicontrol(obj.FileFreqHBox, ...
    'Enable', defaults.enable, ...
    'FontSize', defaults.fontSize, ...
    'Style', 'edit');
obj.FileFreqHBox.Widths = defaults.widths;

obj.MainVBox.Heights = repmat(defaults.height, length(hLabel), 1);

for i = 1:length(hLabel)
    hLabel(i).Position(2) = 7;
end
